name: Dependabot auto-merge
on: pull_request

# Based on https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'flcdrg/get-azure-app-configuration-action'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3.0.0
        continue-on-error: true # Handle 'PR is not from Dependabot, nothing to do' error quietly
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        if: ${{
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          contains(steps.metadata.outputs.dependency-names, 'actions/checkout') ||
          contains(steps.metadata.outputs.dependency-names, 'actions/upload-artifact') ||
          contains(steps.metadata.outputs.dependency-names, 'actions/download-artifact') ||
          contains(steps.metadata.outputs.dependency-names, 'actions/setup-node') ||
          contains(steps.metadata.outputs.dependency-names, 'dependabot/fetch-metadata') ||
          contains(steps.metadata.outputs.dependency-names, 'Azure/login') ||
          contains(steps.metadata.outputs.dependency-names, 'release-drafter/release-drafter') ||
          contains(steps.metadata.outputs.dependency-names, 'peter-evans/create-pull-request') ||
          contains(steps.metadata.outputs.dependency-names, 'actions-tagger/actions-tagger') ||
          contains(steps.metadata.outputs.dependency-names, 'github/codeql-action')
          }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
